### ISSUE TITLE
Preenchimento de colunas

### ISSUE THREAD

**Issue by marcelodosreis** [jeffotoni/work-at-s3wf#3]
As colunas " Data inicial, Hora Inicial, Data Final, Hora Final, Tamanho do csv, Nome Tarefa, Download, Ação;" serao preenchidas pelo "usuario" que ira usar a aplicação, ou quando ele abrir a pagina vai esta tudo pronto e ele so faz o download do arquivo?

**Comment by jeffotoni** [comment]
Opa Marcelo, vamos ver se ajudamos.

Quando o usuário entrar estará tudo vazio "--" somente o "gerar csv" estará ativo e quando ele clicar no "gerar csv" o sistema irá fazer 2 ações: 

**primeira ação**
Guardar no banco usuário, data, hora e o nome-arquivo.csv que irá ser gerado e retornar na tela um loader para o "gerar csv" ficar cinza ou algo do tipo para da entender que está executando 

**segunda ação**
Irá rodar um script.php no shell, para fazer a segunda ação, ele irá setar a tabela que criou avisando que está rodando e que está em andamento  a geração do csv e o script pode fazer o que achar melhor só para simular mesmo pode ser feito um arquivo com qualquer informação, mas tem que dar update na tabela que criou na primeira ação para que o seu while não fique infinito ou seja ler tudo que estiver com status "aguardando" quando entra no while do seu seta para "andamento" e no finalizar do arquivo seta como "concluido" assim o seu "select" não irá ler novamente, agora é só gerar um arquivo em disco, iduser-nomefile.csv, ou seja cada usuário teria um arquivo .csv para download. 
E assim que finalizar e gerar, ele da update nas colunas, data, hora, tamanho e o status é claro como citei acima. Quando o usuário da um F5 na tela ele irá ver o download e os campos que estava "--" com as informações que vc gravou no banco e do arquivo gerado e pronto.

Esperamos ter ajudado.
